config/routes.rb
Forum::Application.routes.draw do

  resources :subforums do 
    resources :fthreads
  end

  resources :posts

  get "home/index"

  root :to => "home#index"
  

end

app/models/fthread.rb
class Fthread < ActiveRecord::Base
  belongs_to :subforum
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/subforum.rb
class Subforum < ActiveRecord::Base

has_many :fthreads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fthreads_controller.rb
class FthreadsController < ApplicationController
  # GET /fthreads
  # GET /fthreads.xml
  def index
    @fthreads = Fthread.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fthreads }
    end
  end

  # GET /fthreads/1
  # GET /fthreads/1.xml
  def show
    @fthread = Fthread.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fthread }
    end
  end

  # GET /fthreads/new
  # GET /fthreads/new.xml
  def new
    @fthread = Fthread.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fthread }
    end
  end

  # GET /fthreads/1/edit
  def edit
    @fthread = Fthread.find(params[:id])
  end

  # POST /fthreads
  # POST /fthreads.xml
  def create
    @subforum=Subforum.find(params[:subforum_id])
    #@fthread = Fthread.new(params[:fthread])
    @fthread= @subforum.fthreads.create(params[:fthread])

    redirect_to subforum_path(@subforum)

    #respond_to do |format|
    # if @fthread.save
    #    format.html { redirect_to(@fthread, :notice => 'Fthread was successfully created.') }
    #    format.xml  { render :xml => @fthread, :status => :created, :location => @fthread }
    #  else
    #   format.html { render :action => "new" }
    #    format.xml  { render :xml => @fthread.errors, :status => :unprocessable_entity }
    #  end
    #end
  end

  # PUT /fthreads/1
  # PUT /fthreads/1.xml
  def update
    @fthread = Fthread.find(params[:id])

    respond_to do |format|
      if @fthread.update_attributes(params[:fthread])
        format.html { redirect_to(@fthread, :notice => 'Fthread was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fthread.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fthreads/1
  # DELETE /fthreads/1.xml
  def destroy
    @fthread = Fthread.find(params[:id])
    @fthread.destroy

    respond_to do |format|
      format.html { redirect_to(fthreads_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @subforums=Subforum.all
  
  
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController
  # GET /subforums
  # GET /subforums.xml
  def index
    @subforums = Subforum.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subforums }
    end
  end

  # GET /subforums/1
  # GET /subforums/1.xml
  def show
    @subforum = Subforum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subforum }
    end
  end

  # GET /subforums/new
  # GET /subforums/new.xml
  def new
    @subforum = Subforum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subforum }
    end
  end

  # GET /subforums/1/edit
  def edit
    @subforum = Subforum.find(params[:id])
  end

  # POST /subforums
  # POST /subforums.xml
  def create
    @subforum = Subforum.new(params[:subforum])

    respond_to do |format|
      if @subforum.save
        format.html { redirect_to(@subforum, :notice => 'Subforum was successfully created.') }
        format.xml  { render :xml => @subforum, :status => :created, :location => @subforum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subforum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subforums/1
  # PUT /subforums/1.xml
  def update
    @subforum = Subforum.find(params[:id])

    respond_to do |format|
      if @subforum.update_attributes(params[:subforum])
        format.html { redirect_to(@subforum, :notice => 'Subforum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subforum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subforums/1
  # DELETE /subforums/1.xml
  def destroy
    @subforum = Subforum.find(params[:id])
    @subforum.destroy

    respond_to do |format|
      format.html { redirect_to(subforums_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fthreads_helper.rb
module FthreadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subforums_helper.rb
module SubforumsHelper
end

app/views/fthreads/_form.html.erb
<%= form_for(@fthread) do |f| %>
  <% if @fthread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fthread.errors.count, "error") %> prohibited this fthread from being saved:</h2>

      <ul>
      <% @fthread.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subforum %><br />
    <%= f.text_field :subforum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fthreads/edit.html.erb
<h1>Editing fthread</h1>

<%= render 'form' %>

<%= link_to 'Show', @fthread %> |
<%= link_to 'Back', fthreads_path %>

app/views/fthreads/index.html.erb
<h1>Listing fthreads</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Subforum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fthreads.each do |fthread| %>
  <tr>
    <td><%= fthread.title %></td>
    <td><%= fthread.subforum %></td>
    <td><%= link_to 'Show', fthread %></td>
    <td><%= link_to 'Edit', edit_fthread_path(fthread) %></td>
    <td><%= link_to 'Destroy', fthread, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fthread', new_fthread_path %>

app/views/fthreads/new.html.erb
<h1>New fthread</h1>

<%= render 'form' %>

<%= link_to 'Back', fthreads_path %>

app/views/fthreads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @fthread.title %>
</p>

<p>
  <b>Subforum:</b>
  <%= @fthread.subforum %>
</p>


<%= link_to 'Edit', edit_fthread_path(@fthread) %> |
<%= link_to 'Back', fthreads_path %>

app/views/home/index.html.erb
<h1>Forum</h1>
<p>Home#index</p>

<%= render "/subforums/index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= #stylesheet_link_tag :all
  stylesheet_link_tag "main" 
  %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= render :partial => "/header" %><div id='main'>

<%= yield %>

</div><%= render :partial => "/footer" %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Author %><br />
    <%= f.text_field :Author %>
  </div>
  <div class="field">
    <%= f.label :Content %><br />
    <%= f.text_area :Content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% @posts.each do |post| %>
  <div class='Post'>
    <span><b>Author:</b><%= post.Author %></span>
    <span>  <b>Utworzony:</b>
  <%= post.created_at.year.to_s+"."+post.created_at.month.to_s+'.'+post.created_at.day.to_s+'  '+post.created_at.hour.to_s+':'+post.created_at.min.to_s
   %></span>
<%
if post.updated_at!=post.created_at %>
<span>
  <b>Zmodyfikowany:</b>
  <%= post.updated_at.year.to_s+"."+post.updated_at.month.to_s+'.'+post.updated_at.day.to_s+'  '+post.updated_at.hour.to_s+':'+post.updated_at.min.to_s
   %>
   
</span>
<% end %>

<span>
  <b>Id:</b>
  <%= post.id %>
</span>    
    
    <br>
    <%= post.Content %><br>
    <%= link_to 'Show', post %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
  </div>
<% end %>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class='Post'>


<p>
<span>
  <b>Author:</b>
  <%= @post.Author %>
</span>

<span>
  <b>Utworzony:</b>
  <%= @post.created_at.year.to_s+"."+@post.created_at.month.to_s+'.'+@post.created_at.day.to_s+'  '+@post.created_at.hour.to_s+':'+@post.created_at.min.to_s
   %>
</span>

<%
if @post.updated_at!=@post.created_at %>
<span>
  <b>Zmodyfikowany:</b>
  <%= @post.updated_at.year.to_s+"."+@post.updated_at.month.to_s+'.'+@post.updated_at.day.to_s+'  '+@post.updated_at.hour.to_s+':'+@post.updated_at.min.to_s
   %>
   
</span>
<% end %>


<span>
  <b>Id:</b>
  <%= @post.id %>
</span>

</p>


<p>
  <b>Content:</b>
  <%= @post.Content %>
</p>

<div class='post_controls'>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %></div>

</div>

app/views/subforums/_form.html.erb
<%= form_for(@subforum) do |f| %>
  <% if @subforum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subforum.errors.count, "error") %> prohibited this subforum from being saved:</h2>

      <ul>
      <% @subforum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subforums/_index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subforums.each do |subforum| %>
  <tr>
    <td><%= subforum.name %></td>
    <td><%= subforum.desc %></td>
    <td><%= link_to 'Show', subforum %></td>
    <td><%= link_to 'Edit', edit_subforum_path(subforum) %></td>
    <td><%= link_to 'Destroy', subforum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subforum', new_subforum_path %>

app/views/subforums/edit.html.erb
<h1>Editing subforum</h1>

<%= render 'form' %>

<%= link_to 'Show', @subforum %> |
<%= link_to 'Back', subforums_path %>

app/views/subforums/new.html.erb
<h1>New subforum</h1>

<%= render 'form' %>

<%= link_to 'Back', subforums_path %>

app/views/subforums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subforum.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @subforum.desc %>
</p>

<h2>Threads</h2>
<% @subforum.fthreads.each do |fthread| %>
  <p>
    <b>Title:</b>
    <%= fthread.title %>
  </p>

<% end %>

<h2>Add a thread:</h2>
<%= form_for([@subforum, @subforum.fthreads.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_subforum_path(@subforum) %> |
<%= link_to 'Back', subforums_path %>